name: Monitor Positions
on:
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install all dependencies from requirements.txt
    
    - name: Run Python script
      env:
        API_KEY: ${{ secrets.TEST_API_KEY }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}  # Email user from GitHub Secrets
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}  # Email password from GitHub Secrets
        EMAIL_TO: ${{ secrets.EMAIL_TO }}      # Email recipient from GitHub Secrets
        TOKEN: ${{ secrets.TOKEN }}      # Email recipient from GitHub Secrets
        userid: ${{ secrets.userid }}
        password: ${{ secrets.password }}
        vendor_code: ${{ secrets.vendor_code }}
        api_secret: ${{ secrets.api_secret }}
        imei: ${{ secrets.imei }}
      run: python3 monitor_trade_safe_v3.py
    - name: Configure git
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "action@github.com"
    - name: Check for changes
      id: git_status
      run: |
        if git diff --quiet; then
          echo "No changes to commit."
        else
          echo "Changes detected."
          git add .
          git commit -m "Update file"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_API_KEY}}
